In [441]:
import numpy as np
import pandas as pd

In [442]:
data=(pd.read_csv('logistic_reg_data.csv'))
data=data.values
np.random.shuffle(data)
x=data[:,1:3]
y=data[:,3].reshape(200,1)
x0=np.ones((200,1))
x=np.hstack((x0,x))
x_train=x[:140]
x_test=x[140:]
y_train=y[:140]
y_test=y[140:]
y_train.shape

(140, 1)

In [443]:
theta=np.random.rand(3,1)


In [444]:
for i in range(1,10000):
    dot_product=np.dot(x_train,theta)
    d=sigmoid(dot_product)
    cost_der=np.dot(x_train.T,(y_train-d))
    theta=theta+(.1*cost_der)


C:\Anaconda\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: overflow encountered in exp
  


In [445]:
y_predict=np.dot(x_test,theta)
y_predict_sig=sigmoid(y_predict)


In [446]:
acc=0
for i in range(60):
    if int(y_predict_sig[i])==int(y_test[i]):
        acc=acc+1
acc=(acc/60)*100
print(acc)

96.66666666666667


array([[ 10507.78332303],
       [ 78649.6387032 ],
       [114784.70626952]])

50.0


array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [325]:
y_predict

array([[23963.61435972],
       [21872.22005492],
       [30832.07102558],
       [20231.16189988],
       [15346.82457086],
       [ 6303.48413142],
       [12922.46354279],
       [13846.02104081],
       [25745.18251999],
       [15865.78028627],
       [26126.62406075],
       [20632.54446033],
       [13939.4038189 ],
       [17217.86458091],
       [15877.35176053],
       [26478.50423116],
       [31051.65013931],
       [22240.07148788],
       [ 8867.74307091],
       [15968.421333  ],
       [29828.10440302],
       [25520.87118337],
       [19856.84344872],
       [18744.28612064],
       [24763.92172454],
       [28059.33343194],
       [28980.07275938],
       [19383.11996201],
       [ 8833.28020895],
       [20645.27753682],
       [ 8141.66604638],
       [27872.29351287],
       [15302.80236157],
       [ 8918.75534193],
       [12565.68844892],
       [28179.74274674],
       [10094.12041874],
       [18043.03164653],
       [12265.65518733],
       [13113.97120964],


(201, 200)

In [130]:
def cost_function(pred,actual,m):
    return -np.sum(actual*np.log(pred)+(1-actual)*np.log(1-pred))/m

In [132]:
cost_function(d,y,201)

0.6896986871243237

In [114]:


def gradient_descent():
    return